<div id="content">
	<h1 class="headline">AmazonS3FileSystem</h1>
	<div id="filepath">Filepath: <em>phork/php/ext/files/AmazonS3FileSystem.class.php</em></div>
	
	<p>The AmazonS3FileSystem class extends the <a href="<?php echo($strBaseUrl); ?>/manual/ext/filesys/LocalFileSystem/">LocalFileSystem</a> class and is used for all file system operations. Instead of working locally it works with files stored on Amazon's S3 system.</p>
	<p>This requires the Zend_Service_Amazon_S3 class from the <a href="http://framework.zend.com/" rel="external">Zend Framework</a> which is included using the <a href="<?php echo($strBaseUrl); ?>/manual/ext/zend/ZendLoader/">ZendLoader</a> class.</p>
</div>