<div id="content">
	<h1 class="headline">DatabaseResource</h1>
	<div id="filepath">Filepath: <em>phork/php/database/DatabaseResource.class.php</em></div>
	
	<p>The DatabaseResource class stores the database connection variables, a flag to determine if the connection is open, and the database resource/object returned from the connection function. By default there's a read and write resource, as well as any others that have been defined in the <a href="<?php echo($strBaseUrl); ?>/manual/install/configuration/#database">database configuration</a>. The resource objects are instantiated in the <a href="<?php echo($strBaseUrl); ?>/manual/database/DatabaseFactory/">DatabaseFactory</a> and stored in the <a href="<?php echo($strBaseUrl); ?>/manual/database/MySql/">MySql</a> (or equivalent) object.</p>
</div>