<div id="content">
	<h1 class="headline">DatabaseAdaptor</h1> 
	<div id="filepath">Filepath: <em>phork/php/database/DatabaseAdaptor.class.php</em></div>
	
	<p>The DatabaseAdaptor class is an abstract class that all SQL adaptors should extend. It implements the Sql interface found at <em>phork/php/database/interfaces/Sql.interface.php</em>.
	<p>In addition to being a straight forward adaptor, each adaptor class has the ability to read from and write to different databases, allowing for <a href="http://en.wikipedia.org/wiki/Database_replication" rel="external">master-slave replication</a>. It's also possible to add other database connections in addition to the standard read and write. All database connections are defined in the <a href="<?php echo($strBaseUrl); ?>/manual/install/configuration/#database">database configuration</a>.</p>
</div>