<div id="content">
	<h1 class="headline">MySql</h1>
	<div id="filepath">Filepath: <em>phork/php/database/mysql/MySql.class.php</em></div>
	
	<p>The MySql class is an adaptor for the <a href="http://us.php.net/mysql" rel="external">MySql database functions</a>. All the database adaptors must implement the Sql interface found at <em>phork/php/database/interfaces/Sql.interface.php</em>.</p>
	<p>The MySql class isn't just a straight forward adaptor, it also has the ability to read from and write to different databases, allowing for <a href="http://en.wikipedia.org/wiki/Database_replication" rel="external">master-slave replication</a>. In addition to the standard read and write databases it's possible to add one or more other database connections all handled from within the same database object.</p>
</div>