<div id="content">
	<h1 class="headline">Conversion</h1>
	<div id="filepath">Filepath: <em>phork/php/utilities/Conversion.class.php</em></div>
	
	<p>The Conversion class is used to convert units of measurement from one format to another. It currently has support to convert from bytes to kB, MB, GB, etc.</p>
	
	<br />
	
	<h2>Example</h2>
	<?php print Markup::formatCode('
		print Conversion::convertBytes($intBytes);
	'); ?>
</div>