<div id="content">
	<h1 class="headline">JsonHelper</h1>
	<div id="filepath">Filepath: <em>phork/php/utilities/JsonHelper.class.php</em></div>
	
	<p>The JsonHelper class is a simple utility to encode and decode data to and from JSON. It attempts to use the Zend's <a href="http://framework.zend.com/manual/en/zend.json.html" rel="external">Zend_Json</a> class if the Zend Framework is installed, otherwise it reverts back to using PHP's <a href="http://us.php.net/json_encode" rel="external">json_encode()</a> and <a href="http://us.php.net/json_decode" rel="external">json_decode()</a> functions.</p>
</div>