<div id="content">
	<h1 class="headline">PasswordHelper</h1>
	<div id="filepath">Filepath: <em>phork/php/utilities/PasswordHelper.class.php</em></div>
	
	<p>The PasswordHelper class is used to encrypt and validate passwords. It uses <a href="http://us.php.net/manual/en/function.hash.php" rel="external">PHP's hash()</a> function and adds an additional salt to the password before encrypting it.</p>
	<p>Because the encryption is one way, the way to validate a password is to re-encrypt it using the same hashing algorithm and salt and see if it matches the already encrypted value.</p>
	
	<br />
	
	<h2>Example</h2>
	<?php print Markup::formatCode('
		//example encrypted output: SHA-1:hyRK7x:af129785ebba5ad73fcc4fa678b482758be2285c
		$strEncrypted = PasswordHelper::encryptPassword(\'secret\');
		
		//compare the encrypted password with the plain text password
		$blnValid = PasswordHelper::validatePassword($strEncrypted, \'secret\');
	'); ?>
</div>