			<?php if (!empty($blnFooterToc)) { ?>
			<div id="footer-toc" class="js-hide">
				<div class="constrained">
					<?php AppRegistry::get('Controller')->includeTableOfContents(); ?>
				</div>
			</div>
			<?php } ?>
			
			<div id="footer-shift"></div>
			
			<div id="footer">
				<div class="constrained">
					<ul id="footer-nav">
						<li id="nav-demo"><a href="<?php echo($strPhorkitUrl); ?>" rel="external">Phork/it Demo</a></li>
						<li id="nav-github"><a href="http://github.com/phork" rel="external">Phork @ Github</a></li>
						<li id="nav-phorklabs"><a href="http://phorklabs.com" rel="external">Phork Labs</a></li>
						<li id="nav-twitter"><a href="http://twitter.com/phorklabs" rel="external">Twitter</a></li>
					</ul>
					
					<div id="footer-blurb">
						This site is powered by <a href="http://phork.org">Phork</a> and <a href="http://phorkit.org" rel="external">Phork/it</a>
					</div>
				</div>
			</div>
		</div>
		
		<?php
			$objController = AppRegistry::get('Controller');
			
			AppLoader::includeUtility('ConcatHelper');
			$objConcatHelper = new ConcatHelper();
			$blnConcat = $objConcatHelper->getConcat();
			
			//minified javascript files include a '.min' suffix (eg. foo.min.js)
			$strMinified = '.min';
			
			print $objConcatHelper->js(array(
				"{$strJsUrl}/lib/jquery/js/jquery-1.5.1.min.js",
				"{$strJsUrl}/lib/jquery/js/jquery-ui-1.8.10.custom.min.js",
				"{$strJsUrl}/lib/jquery/js/jquery.livequery.min.js",
				"{$strJsUrl}/js/common/global" . ($blnConcat ? $strMinified : '') . '.js',
				"{$strJsUrl}/js/themes/{$strTheme}/common/run" . ($blnConcat ? $strMinified : '') . '.js'
			));
						
			if (!empty($arrJavascript)) {
				print $objConcatHelper->js($arrJavascript);
			}
		?>
	</body>
</html>