<div id="header">
	<div id="header-bar"></div>
	<div id="header-content" class="constrained">
		<a id="header-text" class="sprite" href="<?php echo($strBaseUrl); ?>/"><strong><?php echo($strSiteTitle); ?></strong></a>
		<a id="header-logo" class="sprite" href="<?php echo($strBaseUrl); ?>/"><span>Home</span></a>
		
		<ul id="header-nav">
			<li id="nav-started"><a href="<?php echo($strBaseUrl); ?>/manual/">Getting Started</a></li>
			<li id="nav-contents"><a href="<?php echo($strBaseUrl); ?>/manual/contents/">Table of Contents</a></li>
			<li id="nav-phork" class="arrow right"><a href="http://github.com/phork/phork" rel="external">Download Phork</a></li>
			<li id="nav-phorkit" class="arrow right"><a href="http://github.com/phork/phorkit" rel="external">Download Phork/it</a></li>
		</ul>
	</div>
</div>
<div id="header-dots"></div>
<div id="header-shift"></div>