<div id="content">
	<h1 class="headline">CoreModel</h1>
	<div id="filepath">Filepath: <em>phork/php/core/CoreModel.class.php</em></div>
	
	<p>The CoreModel class is an abstract class that most models should extend. It sets up the <a href="<?php echo($strBaseUrl); ?>/manual/core/CoreIterator/">iterator object</a>, includes the <a href="<?php echo($strBaseUrl); ?>/manual/core/CoreRecord/">record class</a>, and contains all the function to set up the helpers.</p>
	<p>Currently the only built in extension is the <a href="<?php echo($strBaseUrl); ?>/manual/core/CoreDatabaseModel/">CoreDatabaseModel</a> class. As the name suggests this works with data stored in a database. Another type of extension could be an XML model or a model to get data from an API.</p>
</div>