<div id="content">
	<h1 class="headline">CoreStatic</h1>
	<div id="filepath">Filepath: <em>phork/php/core/CoreStatic.class.php</em></div>
	
	<p>The CoreStatic class is an abstract class that most static classes should extend. This is used with a lot of the utility classes. It includes a <strong>__construct()</strong> method that throws a <a href="<?php echo($strBaseUrl); ?>/manual/core/CoreException/">CoreException</a> in the event that the class is instantiated.</p>
</div>