<div id="content">
	<h1 class="headline">CoreObject</h1>
	<div id="filepath">Filepath: <em>phork/php/core/CoreObject.class.php</em></div>
	
	<p>The CoreObject class is an abstract class that most core classes should extend. It includes a <strong>__toString()</strong> method to return the class name of the object and it throws a <a href="<?php echo($strBaseUrl); ?>/manual/core/CoreException/">CoreException</a> for any invalid method calls.</p>
</div>